version: "3"

services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - '5006:5006'
    # environment:
      # Uncomment any of the lines below to set configuration options.
      # - ACTUAL_HTTPS_KEY=/data/selfhost.key
      # - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      # - ACTUAL_PORT=5006
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
      # !! If you are not using any of these options, remove the 'environment:' tag entirely.
    volumes:
      - ./data:/data
    restart: unless-stopped

  unzip-db:
    image: alpine    
    command:
      - /bin/sh
      - -c
      - |
        unzip -o /data/user-files/*.blob -d /data/db 
        sleep 30        
    volumes:
      - ./data:/data
    restart: always

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana    
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
    volumes:
      - ./grafana-config/provisioning:/etc/grafana/provisioning
      - ./grafana-config/dashboards:/var/lib/grafana/dashboards
      - ./data:/data
    restart: unless-stopped
    depends_on:
      - unzip-db